CREATE TABLE books (
book_id BIGSERIAL PRIMARY KEY,
title VARCHAR(128) NOT NULL,
author VARCHAR(128) NOT NULL,
isbn VARCHAR(128) UNIQUE NOT NULL,
cover VARCHAR(128),
pages INTEGER,
price NUMERIC NOT NULL,
rating NUMERIC
);